# === 第一阶段：编译 Node ===
FROM node:18-alpine AS builder

WORKDIR /app

COPY frontend/package*.json ./
RUN npm install

COPY frontend/ ./
RUN npm run build

# === 第二阶段：部署 Nginx ===
FROM nginx:alpine

# 拷贝编译完成的纯静态文件到 nginx html 目录
COPY --from=builder /app/dist /usr/share/nginx/html

# 覆盖自定义反代配置文件，此举打通跨域限制
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
