version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      network: host
    container_name: yolo_backend
    restart: always
    volumes:
      - ./backend/data:/app/backend/data
      - ./backend/snapshots:/app/backend/snapshots
    # ports:
    #   - "8000:8000" # Not needed for external exposure since Nginx handles it
    environment:
      - TZ=Asia/Shanghai
    networks:
      - default
      - 1panel-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      network: host
    container_name: yolo_frontend
    restart: always
    ports:
      - "10080:80"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - default
      - 1panel-network

networks:
  default:
  1panel-network:
    external: true
